// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 3
// RUN: %clang -S -emit-llvm %include_dirs %loadintelclangextensions  %s -o - | FileCheck %s --dump-input fail


#include "clang/Quantum/quintrinsics.h"

// CHECK-LABEL: define dso_local noundef i32 @main(
// CHECK-SAME: ) #[[ATTR2:[0-9]+]] {
// CHECK:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[Q:%.*]] = alloca [4 x i16], align 2
// CHECK-NEXT:    [[C:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [4 x i16], ptr [[Q]], i64 0, i64 0
// CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [4 x i16], ptr [[Q]], i64 0, i64 1
// CHECK-NEXT:    call void @_Z2CZRtS_(ptr noundef nonnull align 2 dereferenceable(2) [[ARRAYIDX]], ptr noundef nonnull align 2 dereferenceable(2) [[ARRAYIDX1]])
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds [4 x i16], ptr [[Q]], i64 0, i64 2
// CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds [4 x i16], ptr [[Q]], i64 0, i64 0
// CHECK-NEXT:    call void @_Z4CNOTRtS_(ptr noundef nonnull align 2 dereferenceable(2) [[ARRAYIDX2]], ptr noundef nonnull align 2 dereferenceable(2) [[ARRAYIDX3]])
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds [4 x i16], ptr [[Q]], i64 0, i64 0
// CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds [4 x i16], ptr [[Q]], i64 0, i64 1
// CHECK-NEXT:    call void @_Z2CZRtS_(ptr noundef nonnull align 2 dereferenceable(2) [[ARRAYIDX4]], ptr noundef nonnull align 2 dereferenceable(2) [[ARRAYIDX5]])
// CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds [4 x i16], ptr [[Q]], i64 0, i64 0
// CHECK-NEXT:    call void @_Z5MeasZRtRbb(ptr noundef nonnull align 2 dereferenceable(2) [[ARRAYIDX6]], ptr noundef nonnull align 1 dereferenceable(1) [[C]], i1 noundef zeroext false)
// CHECK-NEXT:    ret i32 0
//
int main() {
  qbit q[4];
  cbit c;
  //CU(q1,q2)CX(q3,q1)CU(q1,q2)=CU(q3,q2)CX(q3,q1)
  CZ(q[0], q[1]);
  CNOT(q[2], q[0]);
  CZ(q[0], q[1]);

  MeasZ(q[0], c);
  return 0;

  // expected reduction
  // CZ(q[2],q[1]);
  // CNOT(q[2],q[0]);
}

/* NOTE: The validation of the global annotations corresponding to quintrinsic functions is covered in other test(s). */





























